# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: activate environment
          command: |
            python3 -m venv venv
            . venv/bin/activate

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m unittest

      - store_artifacts:
          path: test-reports
          destination: test-reports
